### ISSUE TITLE
Bad base url path formulation when running on windows 10

### ISSUE THREAD

**Issue by gabrielpsz** [tuhrig/Flying_Saucer_PDF_Generation#4]
Java 1.8
IDE: IntelliJ IDEA 2018.1.2 x64

When I try to run the unit test with IntelliJ, I face a problem when rendering the CSS and bar code resources. It was not possible to get both rendered on the PDF test file. I just figured it out when I have changed the baseUrl String. 

> String baseUrl = file:///C:/blablabla/Flying_Saucer_PDF_Generation/src/test/resources/";

**Comment by tuhrig** [comment]
I've pushed an update on "master". Could you please take a look if it fixed the problem? I don't have a Windows machine, so I cannot test it.

**Comment by gabrielpsz** [comment]
Yeah, it's working fine right now :)

**Comment by Silver-Snitch** [comment]
Hey, mind sharing the fix? I am using a different template engine along with flying saucers and am facing the same issue.
